# Configurations
title:            Let's Play
longtitle:        "Let's Play - Videospielkultur und die Generationen / La culture du jeu vidéo et les générations"
author:           Adrian Demleitner
email:            adrian.demleitner@hkb.bfh.ch
description:      "Diese Texte begleiten die Ausstellung “Let’s play! Videospielkultur in der Schweiz”. Ces textes accompagnent l’exposition “Let’s play ! La culture du jeu vidéo en Suisse”."

version:          1.0
gitbook_version:  3.2.3

url:              'https://thgie.github.io'
baseurl:          '/lets-play'
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min:   1
  h_max:   3

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - pages

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
